version: "3.0"

services:
  database:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - rede-cep

  backend:
    image: cep-app:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - rede-cep

networks:
  rede-cep:
    driver: bridge
    name: rede-cep

