version: "3.9"

services:
  database:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - rede-cep

  backend:
    image: cep-backend:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - rede-cep

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - database
    command: tcp database:3306 -t 600s -i 30s
    networks:
      - rede-cep

networks:
  rede-cep:
    driver: bridge
    name: rede-cep

